export default function TermsPage() {
  return (
    <div className="min-h-screen bg-terminal-bg text-terminal-text font-mono px-4 py-10">
      <div className="max-w-3xl mx-auto space-y-8">
        <div>
          <a href="/" className="text-terminal-accent text-xs tracking-widest hover:underline">← BACK TO GEOTRADER</a>
          <h1 className="text-terminal-accent text-xl font-bold tracking-widest mt-4">TERMS OF SERVICE</h1>
          <p className="text-terminal-dim text-xs mt-1">Last updated: March 2026 · © Kavi Godithi. All Rights Reserved.</p>
        </div>

        <Section title="1. Acceptance of Terms">
          By accessing or using GeoTrader ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform. These terms constitute a binding legal agreement between you and Kavi Godithi ("GeoTrader", "we", "us").
        </Section>

        <Section title="2. Not Financial Advice — Important Disclaimer">
          <strong className="text-terminal-sell">GeoTrader is an informational platform only.</strong> All signals, scores, confidence levels, and market commentary generated by the Platform are algorithmic outputs derived from publicly available news sources. Nothing on this Platform constitutes financial advice, investment advice, investment research, or a recommendation to buy, sell, or hold any financial instrument, security, commodity, currency, or cryptocurrency. GeoTrader is not authorised or regulated by the Financial Conduct Authority (FCA), the U.S. Securities and Exchange Commission (SEC), or any other financial regulatory authority. You should always seek independent, qualified financial advice before making any investment decision. Trading involves significant risk of loss, including the possible loss of all capital invested.
        </Section>

        <Section title="3. Eligibility">
          You must be at least 18 years of age to use the Platform. By registering, you confirm that you are 18 or older and that your use of the Platform complies with all laws applicable in your jurisdiction. The Platform is not intended for use by persons in jurisdictions where such use would be contrary to local law or regulation. U.S. persons are advised that the Platform is not registered with the SEC and is not directed at U.S. residents.
        </Section>

        <Section title="4. User Accounts">
          You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately if you believe your account has been compromised. We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behaviour, or use the Platform for automated trading bots or commercial data extraction.
        </Section>

        <Section title="5. No Liability for Trading Losses">
          GeoTrader, its owner, and contributors accept no liability whatsoever for any financial loss, trading loss, or any other loss arising from your use of or reliance on information provided by the Platform. All use is entirely at your own risk.
        </Section>

        <Section title="6. Subscriptions and Payments">
          Where subscription plans are offered, billing is processed by Stripe. You agree to the billing cycle stated at purchase. You may cancel at any time; cancellation takes effect at the end of the current billing period. Refunds are not provided for partial periods unless required by applicable consumer law. In the UK, statutory cancellation rights for digital services may apply where the service has not yet been accessed.
        </Section>

        <Section title="7. Intellectual Property">
          All content on this Platform, including signals, UI, algorithms, branding, and source code, is the exclusive property of Kavi Godithi and is protected by copyright and applicable intellectual property law. You may not copy, reproduce, scrape, resell, or redistribute any content from the Platform without prior written permission.
        </Section>

        <Section title="8. Acceptable Use">
          You agree not to: (a) use automated tools to scrape or extract data from the Platform; (b) reverse-engineer or copy the Platform's algorithms or signals; (c) use the Platform in any way that violates applicable law; (d) attempt to gain unauthorised access to any part of the Platform or its infrastructure.
        </Section>

        <Section title="9. Governing Law">
          These Terms are governed by the laws of England and Wales. Any disputes arising from your use of the Platform shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </Section>

        <Section title="10. Changes to Terms">
          We may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated Terms.
        </Section>

        <Section title="11. Contact">
          For questions about these Terms, contact: <a href="mailto:gourinathgodithi@gmail.com" className="text-terminal-accent hover:underline">gourinathgodithi@gmail.com</a>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-terminal-accent text-sm font-bold tracking-widest mb-2">{title}</h2>
      <p className="text-terminal-dim text-sm leading-relaxed">{children}</p>
    </div>
  );
}
