export default function TermsPage() {
  return (
    <div className="min-h-screen bg-terminal-bg text-terminal-text font-mono px-4 py-10">
      <div className="max-w-3xl mx-auto space-y-8">
        <div>
          <a href="/" className="text-terminal-accent text-xs tracking-widest hover:underline">← BACK TO GEOTRADER</a>
          <h1 className="text-terminal-accent text-xl font-bold tracking-widest mt-4">TERMS OF SERVICE</h1>
          <p className="text-terminal-dim text-xs mt-1">Last updated: June 2026 · © Kavi Godithi. All Rights Reserved.</p>
        </div>

        <Section title="1. Acceptance of Terms">
          By accessing or using GeoTrader ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform. These terms constitute a binding legal agreement between you and Kavi Godithi ("GeoTrader", "we", "us").
        </Section>

        <Section title="2. Not Financial Advice — Important Disclaimer">
          <strong className="text-terminal-sell">GeoTrader is an informational and educational platform only.</strong> All signals, scores, confidence levels, and market commentary generated by the Platform are algorithmic outputs derived from publicly available news sources. Nothing on this Platform constitutes financial advice, investment advice, investment research, trading advice, or a recommendation to buy, sell, or hold any financial instrument, security, commodity, currency, or cryptocurrency.{"\n\n"}
          GeoTrader is <strong>NOT</strong> registered with or regulated by the U.S. Securities and Exchange Commission (SEC), the Financial Industry Regulatory Authority (FINRA), the Commodity Futures Trading Commission (CFTC), the Financial Conduct Authority (FCA), or any other financial regulatory authority in any jurisdiction. GeoTrader is not a registered investment adviser, broker-dealer, commodity trading adviser, or investment company.{"\n\n"}
          The virtual portfolio feature is provided solely for educational and simulation purposes. No real money is used, no real trades are executed, and past virtual performance does not indicate future results. You should always seek independent advice from a qualified and regulated financial adviser before making any investment decision. Trading involves significant risk of loss, including the possible loss of all capital invested.
        </Section>

        <Section title="3. SEC / FINRA Notice for U.S. Users">
          If you are a resident of the United States: GeoTrader does not provide personalised investment advice and is not registered with the SEC or FINRA. The Platform does not recommend specific securities or investment strategies. Information provided is general and educational in nature. Under Section 202(a)(11) of the Investment Advisers Act of 1940, GeoTrader does not meet the definition of an investment adviser as it does not receive compensation for providing personalised investment advice. U.S. users should consult a FINRA-registered broker-dealer or SEC-registered investment adviser for personalised financial guidance. To verify the registration status of any financial professional, visit <strong>brokercheck.finra.org</strong>.
        </Section>

        <Section title="4. Eligibility">
          You must be at least 18 years of age to use the Platform. By registering, you confirm that you are 18 or older and that your use of the Platform complies with all laws applicable in your jurisdiction. The Platform is not intended for use by persons in jurisdictions where such use would be contrary to local law or regulation.
        </Section>

        <Section title="5. User Accounts">
          You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately if you believe your account has been compromised. We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behaviour, or use the Platform for automated trading bots or commercial data extraction.
        </Section>

        <Section title="6. No Liability for Trading Losses">
          GeoTrader, its owner, and contributors accept no liability whatsoever for any financial loss, trading loss, or any other loss arising from your use of or reliance on information provided by the Platform. All algorithmic signals are experimental and may be inaccurate. Past signal performance does not guarantee future results. All use is entirely at your own risk.
        </Section>

        <Section title="7. Subscriptions and Payments">
          Where subscription plans are offered, billing is processed by Stripe, Inc. You agree to the billing cycle stated at purchase. You may cancel at any time; cancellation takes effect at the end of the current billing period. Refunds are not provided for partial periods unless required by applicable consumer law. GeoTrader does not store your payment card details — all payment processing is handled exclusively by Stripe.
        </Section>

        <Section title="8. California Consumer Privacy Act (CCPA)">
          If you are a California resident, you have the following rights under the CCPA: (a) the right to know what personal information we collect about you; (b) the right to delete your personal information; (c) the right to opt out of the sale of your personal information. GeoTrader does NOT sell your personal information to third parties. To exercise any of these rights, contact us at gourinathgodithi@gmail.com. We will respond within 45 days as required by law.
        </Section>

        <Section title="9. Intellectual Property">
          All content on this Platform, including signals, UI, algorithms, branding, and source code, is the exclusive property of Kavi Godithi and is protected by copyright and applicable intellectual property law. You may not copy, reproduce, scrape, resell, or redistribute any content from the Platform without prior written permission.
        </Section>

        <Section title="10. Acceptable Use">
          You agree not to: (a) use automated tools to scrape or extract data from the Platform; (b) reverse-engineer or copy the Platform's algorithms or signals; (c) use the Platform in any way that violates applicable law; (d) attempt to gain unauthorised access to any part of the Platform or its infrastructure; (e) use the Platform for any unlawful purpose including market manipulation.
        </Section>

        <Section title="11. Governing Law">
          These Terms are governed by the laws of England and Wales. For U.S. users, any disputes shall be resolved by binding arbitration under the rules of the American Arbitration Association, waiving the right to a jury trial or class action. Nothing in this clause limits your statutory rights under applicable consumer protection laws.
        </Section>

        <Section title="12. Changes to Terms">
          We may update these Terms at any time. We will notify registered users of material changes by email. Continued use of the Platform after changes constitutes acceptance of the updated Terms.
        </Section>

        <Section title="13. Contact">
          For questions about these Terms, SEC/FINRA inquiries, or CCPA requests, contact: <a href="mailto:gourinathgodithi@gmail.com" className="text-terminal-accent hover:underline">gourinathgodithi@gmail.com</a>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-terminal-accent text-sm font-bold tracking-widest mb-2">{title}</h2>
      <p className="text-terminal-dim text-sm leading-relaxed">{children}</p>
    </div>
  );
}
